// examples/react/apollo-client/src/App.tsx
import React from 'react';
import { useQuery } from '@apollo/client';
import './App.css';
import Film from './Film';
import { graphql } from './gql/gql';

const allFilmsWithVariablesQueryDocument = graphql(/* GraphQL */ `
  query allFilmsWithVariablesQuery($first: Int!) {
    allFilms(first: $first) {
      edges {
        node {
          ...FilmItem
        }
      }
    }
  }
`);

function App() {
  const { data } = useQuery(allFilmsWithVariablesQueryDocument, { variables: { first: 10 } });
  return (
    <div className="App">
      {data && (
        <ul>
          {data.allFilms?.edges?.map(
            (e, i) => e?.node && <Film film={e?.node} key={`film-${i}`} />,
          )}
        </ul>
      )}
    </div>
  );
}

export default App;

// examples/vue/villus/src/App.vue
<script setup lang="ts">
import { useClient, useQuery } from 'villus';
import { computed } from 'vue';
import FilmItem from './components/FilmItem.vue';
import { graphql } from './gql';

useClient({
  url: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
});

const { data } = useQuery({
  query: graphql(/* GraphQL */ `
    query allFilmsWithVariablesQuery($first: Int!) {
      allFilms(first: $first) {
        edges {
          node {
            ...FilmItem
          }
        }
      }
    }
  `),
  variables: { first: 10 },
});
const films = computed(() => data.value?.allFilms?.edges?.map(e => e?.node!));
</script>

<template>
  <ul>
    <li v-for="film of films"><FilmItem :film="film" /></li>
  </ul>
</template>
